<template>
  <div class="loadingio-spinner-magnify-1eelxem743o">
    <div class="ldio-jiy360upoy">
      <div>
        <div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
</template>
<style>
@keyframes ldio-jiy360upoy {
  0% {
    transform: translate(2px, 2px);
  }
  33.33% {
    transform: translate(102px, 2px);
  }
  66.66% {
    transform: translate(42px, 102px);
  }
  100% {
    transform: translate(2px, 2px);
  }
}

.ldio-jiy360upoy > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-jiy360upoy > div > div {
  animation: ldio-jiy360upoy 1s linear infinite;
  position: absolute;
}

.ldio-jiy360upoy > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #564b4f;
  background: #eff1f2;
}

.ldio-jiy360upoy > div > div div:nth-child(2) {
  width: 17px;
  height: 51px;
  transform: rotate(-45deg);
  background: #564b4f;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px;
}
.loadingio-spinner-magnify-1eelxem743o {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-jiy360upoy {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-jiy360upoy div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
